### ISSUE TITLE
Notification not clearing when the app is reinstalled

### ISSUE THREAD

**Issue by ashishnandwani** [katzer/cordova-plugin-badge#100]
For some reason the badge doesn't clear even if we reinstall the app. Am I missing something here?
Does it store the badge in local storage?

**Comment by katzer** [comment]
@ashishnandwani 

You're talking about Android? Sounds like a manufacturer specific behaviour. Otherwise the plugin clears the badge if you start the app and have set `autoClear` to `true`.

**Comment by ashishnandwani** [comment]
Hello! Thanks for replying! In the documentation it says it's going to clear the badge when we tap on the app as well? I actually was using this to set the number of offline apps stored in the DB of the device and I wanted the number to be there and should go only when the app is installed again or can be updated whenever the count increases. And I'm talking about IOS, Do you suggest I use something else here or should I try the autoClear?

**Comment by katzer** [comment]
> In the documentation it says it's going to clear the badge when we tap on the app

Yes, if you have set autoClear to true.

But if you set a badge, reinstall the plugin and the badge is still there, then it wasn't set by the plugin.
