### ISSUE TITLE
not getting notification badge in phonegap app

### ISSUE THREAD

**Issue by webtestdeveloper** [katzer/cordova-plugin-badge#101]
hello,
I am using xiomi MI 5 device. And I am building app in phonegap. I am not getting notification badge. 

check my code.
function onDeviceReady() {
        cordova.plugins.notification.badge.hasPermission(function (granted) {
    	      alert("hasPermission granted"+ granted);
	});
	cordova.plugins.notification.badge.set(10);
}

**Comment by katzer** [comment]
@webtestdeveloper The real action is handled by the https://github.com/leolin310148/ShortcutBadger lib. The code looks ok. If you still can't see the badge, then ShortcutBadger cannot set the badge for (unknown) reason.

**Comment by kernelogic** [comment]
There is a WIKI on shortcutbadge saying xiaomi requires special treatement
https://github.com/leolin310148/ShortcutBadger/wiki/Xiaomi-Device-Support

@katzer  do you support this?

**Comment by webloper** [comment]
Dealing with same issue, every thing is working fine except I can't see badges. 
Tried [isBadgeWorking](https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking) and report issue related this @katzer @kernelogic
