### ISSUE TITLE
Dropped iOS9 support with the introduction of UNUserNotificationCenter?

### ISSUE THREAD

**Issue by mad-nuts** [katzer/cordova-plugin-badge#102]
As far as I am aware, UNUserNotificationCenter is only available on iOS 10 and later.

calling ...

- set
- hasPermission
- requestPermission

... triggers one of ...

`UNUserNotificationCenter *center = UNUserNotificationCenter.currentNotificationCenter;`
`[center getNotificationSettingsWithCompletionHandler]` /
`[center requestAuthorizationWithOptions:options completionHandler]`

... which works fine on iOS10 and above, but the completion handlers are never called on iOS9 and below.

**Comment by katzer** [comment]
Hi @mad-nuts, support for iOS 9 has been dropped with v0.8 - see the changelog. If you need to target iOS 9 you will have to use v0.7

**Comment by mad-nuts** [comment]
Ah there it is, completely missed the iOS9 note in the changelogs.
Sorry for that and thank you for the quick response. I'm closing the issue.
