### ISSUE TITLE
0.8.5 Not working on Android (even via example app - but works via IsBadgeWorking)

### ISSUE THREAD

**Issue by KholofeloMoyaba** [katzer/cordova-plugin-badge#104]
Version 0.8.5 is not working on my project on android. To isolate the issue, I used the example project (https://github.com/katzer/cordova-plugin-badge/tree/example). I realised that even that doesn't work out of the box, however, the ShortcutBadger tool (isBadgeWorking) works on the same device.

I've noticed that isBadgeWorking runs on ShortcutBadger 1.1.18 (as opposed to 1.1.19) - so I tried to downgrade to 1.1.18 but that also didn't work. I've looked at the closed issues for some direction but so far it didn't help - was particularly looking at https://github.com/katzer/cordova-plugin-badge/issues/79

See below a screenshot of the example project vs isBadgeWorking:
![screenshot_20171114-000425](https://user-images.githubusercontent.com/4819593/32752091-914d416c-c8d0-11e7-8a60-66b8086d6596.png)

See below the device specs (if that helps):
![screenshot_20171114-000441](https://user-images.githubusercontent.com/4819593/32752108-a0cc2ac2-c8d0-11e7-91b7-fe7ba75c64f0.png)

Any help would be appreciated, been stuck on this for a while.

**Comment by KholofeloMoyaba** [comment]
@katzer please are you able to provide some assistance here?

**Comment by katzer** [comment]
Hi, if you know how to debug then you could help me solving this. Maybe its just an configuration issue on your phone (app permissions).

**Comment by katzer** [comment]
The IsBadgingWorking App doesn't do much more then the plugin itself. There's only one way to set the badge. I could never reproduce that.

**Comment by KholofeloMoyaba** [comment]
Thanks for the reply @katzer. 
I've tried doing some debugging. Will continue doing some more tests then get back to you.
As for the example app, I installed it as is - I was hoping for it to work out of the box? Does the example app work on an Android for you?

**Comment by KholofeloMoyaba** [comment]
Hi @katzer:
Please see this line from the error logs:
```bash
11-16 12:17:11.477 29215-5315/de.appplant.cordova.plugin.badge.example E/ActivityThread: Failed to find provider info for com.teslacoilsw.notifier
```

it seems `Failed to find provider info for com.teslacoilsw.notifier` this might be the indicative error. This is just to keep you updated, doing more tests.

**Comment by KholofeloMoyaba** [comment]
@katzer I found what the issue was.
The Nova launcher (https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en) was installed on the device (even though it wasn't being used). As such the plugin was looking for the other package that enabled badging on the Nova launcher (com.teslacoilsw.notifier).

The quick remedy was just to uninstall the Nova launcher. The badging worked properly - still weird that isBadgeWorking was working either way - so probably extra configs on the plugin.

I'll close this issue now.

@katzer If I may ask a slightly unrelated issue. Is it possible to use this plugin along with firebase push notifications such that the badge is updated depending on the payload sent via firebase?

**Comment by katzer** [comment]
Usually yes, also other plugins can use the badge plugin as a lib. The local-notification plugin is doing so with v0.9-beta to set the badge
