### ISSUE TITLE
Native: tried calling Badge.registerPermission, but the Badge plugin is not installed.

### ISSUE THREAD

**Issue by dalezak** [katzer/cordova-plugin-badge#105]
Running into an issue trying to use the plugin with `ionic-angular 3.9.2` and `@ionic-native/badge 4.3.3`.

```
Native: tried calling Badge.registerPermission, but the Badge plugin is not installed.
Install the Badge plugin: 'ionic cordova plugin add cordova-plugin-badge'
```

I believe it's related to the issue https://github.com/ionic-team/ionic-native/issues/1856.

**Comment by PavlezT** [comment]
I have the same problem and it is very annoying, because I need to build a release of app! But unfortunately I can`t(

**Comment by PavlezT** [comment]
I use such call of registerPermission
`cordova.plugins.notification.badge.registerPermission(function(text){console.log('permis:',text)});`

It worked for me.
And important, that I have changed my **User-Agent**, so script couldn't get that this is IPad or iPhone.

**Comment by a-faraz** [comment]
Hello, 
I am using 
ionic#1.3.5,
angular#1.4.3,
cordova#8.0.0
With the latest version of this plugin.
It was working fine before however suddenly stopped working. I am not sure if it is a permissions (xcode) thing or something with this plugin. 
Testing on iPhone iOS 10.



Can anyone help?


```  angular.module('tabs')
  .controller('TabsCtrl', function ($scope, $window, $ionicPlatform, $cordovaBadge) {


      function setOnIcon (count) {
        $ionicPlatform.ready(function () {
          // alert(JSON.stringify('$cordova ',  $cordovaBadge));
          // alert(JSON.stringify('cordova ', $window.cordova.plugins));
          if ($window.cordova) {
            $window.cordova.plugins.notification.badge.requestPermission(function (text) { console.log('text:', text)});
            $window.cordova.plugins.notification.badge.set(count);
            $cordovaBadge.requestPermission(function(granted) { return; });
            $cordovaBadge.set(count);
          }
        });
      }
    }```

The alerts come back as empty. I am pretty sure the plugin is not being called at all.

**Comment by katzer** [comment]
The method you are trying to call is `requestPermission(...)`

**Comment by danielsogl** [comment]
Fixed in the ionic-native wrapper. You can close this issue.
