### ISSUE TITLE
Question: Not Working on IOS 9 and Can we custom the badge notification??

### ISSUE THREAD

**Issue by budidao** [katzer/cordova-plugin-badge#108]
badge notif not showing on IOS 9? anyone can help me??

and Is it possible to custom the background color of the notification and add white border? 
Because current icon is also red color and not look so good.

**Comment by katzer** [comment]
Hello @budidao 

> badge notif not showing on IOS 9?

The plugin only supports iOS10+ For iOS 9 you need to use an older version of the plugin.

> Is it possible to custom the background color of the notification and add white border?

Thats not possible

**Comment by Grohden** [comment]
> The plugin only supports iOS10+ For iOS 9 you need to use an older version of the plugin.

@katzer could you specify that in the **README**? I've lost some hours till i found this issue..

Which version supports iOS9? does that iOS9 version supports iOS10+ too?

**Comment by katzer** [comment]
I've updated the README - Also take a look into the changelog.

Support for iOS 10 came with v0.7.3 and since v0.8.x only iOS 10+ is supported. Might be possible that older versions might crash with iOS 11 due API changes.

**Comment by FishSaidNo** [comment]
Hi, I have a Meteor project and am wondering how to update a project's apple-ios version?

To avoid this:
`%% Plugin doesn't support this project's apple-ios version. apple-ios: 9.2.0, failed version requirement: >=10.0.0`
`%% Skipping 'cordova-plugin-badge' for ios`

I have tried setting
`App.setPreference('deployment-target', '10.0');`
 in mobile-config.js, which translates to the deployment target in XCode.

However this has no effect on the error

**Comment by FishSaidNo** [comment]
@katzer Nowhere in my project is an iOS deployment target of 9.2 even mentioned. However, my version of Xcode is 9.2 (which is the most recent) perhaps this is where the issue is coming from.

In the plugin.xml file there is
`<engine name="apple-ios" version=">=10.0.0" />`
Should this perhaps be
`<engine name="cordova-ios" version=">=x.x.x" />`
