### ISSUE TITLE
badge set method not working

### ISSUE THREAD

**Issue by jatinbphp** [katzer/cordova-plugin-badge#109]
Hello,

i have issue incordova.plugins.notification.badge.set(10);
It is not setting badge on icon.
Whenever i receive push notification, it always display 1 default.
Even increment method is also not works.Please help on this.

**Comment by katzer** [comment]
@jatinbphp Please provide more infos such like plugin version, platform, platform version, ...

**Comment by jatinbphp** [comment]
Hello @katzer  Thanks for your reply. Now i am facing one strange issue.

badge.set was working. i set it 8 statically, but after i remove that code and generate new app, it still shows same 8 , do you have any idea why that is happening.

**Comment by katzer** [comment]
Thats native OS behaviour
