### ISSUE TITLE
Badge count not working on all device

### ISSUE THREAD

**Issue by jatinbphp** [katzer/cordova-plugin-badge#110]
Hello, Badge count is not working on all android device.
It works on some device perfectly and not work on some android device.
I have installed it on android.
Also, earlier , i set badge count as 8  and i remove it as well, but it still showing same 8 as static badge count even i have reinstalled new app where i removed that code.
Do you have any idea how i can fix both those issue ?

**Comment by katzer** [comment]
@jatinbphp What you are describing is the native behaviour of the underlying OS or launcher. 

Additionally I've added a runtime method to check the support for badging the app icon.
