### ISSUE TITLE
Unable to get property 'versionInfo' of undefined or null reference

### ISSUE THREAD

**Issue by andreszs** [katzer/cordova-plugin-badge#113]
On the latest version 0.8.7, I am getting this error on a Windows Phone 8.1 device:

> 0x800a138f - JavaScript runtime error: Unable to get property 'versionInfo' of undefined or null reference

This error has been introduced on version 0.8.4 after adding this to www/badge.js: ([compare](https://github.com/katzer/cordova-plugin-badge/commit/056fc5cd0f672e4b86c5a6c5b47e264bb9876349#diff-a4df28e873ad792c41ebaf8978b0a35b))

`isWinPC   = isWin && Windows.System.Profile.AnalyticsInfo.versionInfo.deviceFamily.includes('Desktop'),`

It seems this versionInfo method is exclusive from Windows 10 Mobile, could we please remove it somehow so we can still support Windows Phone 8.1 devices?

**Comment by katzer** [comment]
@andreszs There's no support for Windows Phone 8.1
