### ISSUE TITLE
Blackberry PRIV @ Android 6.0.1

### ISSUE THREAD

**Issue by GitStorageOne** [katzer/cordova-plugin-badge#115]
Hello! 
I use plugin with IONIC3, unfortunately it not work with blackberry PRIV @android 6.0.1.
Tested same APK on other devices even with same android version - sony, samsung works fine.

Is there anything that can be done to add blackberry support?

**Comment by katzer** [comment]
@GitStorageOne Please be a bit more precise. What's not working?

I guess you mean that displaying badges doesn't work. BlackBerry Android uses a customised launcher (like many others are doing) which does not have badge numbers. Maybe only the asterix if its working equal to BB10 OS. Instead the Hub is the central space for messages and notifications.

See ShortcutBadger for a list of supported devices/launchers.

**Comment by GitStorageOne** [comment]
Hello!

> Please be a bit more precise. What's not working?

No badge on the application icon, while method "set" returns success.
```
      this.badge.set(10).then(res => {
        console.log('ok ' + res);
      }).catch(reason => {
        console.log('err :( ' + reason);
      })
```

> BlackBerry Android uses a customised launcher (like many others are doing) which does not have badge numbers. Maybe only the asterisk if its working
See ShortcutBadger for a list of supported devices/launchers.

You right. I missed that you use another project for android platform :(
Well, launcher indeed supports asterisk, but seems nothing to do.

![sample](https://user-images.githubusercontent.com/3978064/37095304-8e5d14b4-2226-11e8-8c6d-c87025c76a68.PNG)
