### ISSUE TITLE
Plugin doesn't support cordova-android 7.x

### ISSUE THREAD

**Issue by kareraisu** [katzer/cordova-plugin-badge#117]
Hello there!

The latest cordova-android major version updated the file structure of the android project, changing the location of several files, like the manifest. Thus several plugins broke, including this one. Please update the plugin accordingly to account for the new file structure.

Links:
- [cordova-android 7 announcement](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)
- [structure change jira issue](https://issues.apache.org/jira/browse/CB-11244)

**Comment by Dimigergo** [comment]
I have the same problem.
Thanks!

**Comment by htsnet** [comment]
+1

**Comment by AndreasDickow** [comment]
+1

**Comment by f5cs** [comment]
hi kareraisu,
    do you have soulution? the author maybe not mataince this plugin.

**Comment by katzer** [comment]
What's the error? I am running cordova-android 7.1.2 with the plugin without any issues during the installation.
