### ISSUE TITLE
not working with android 6.0 or 7.0

### ISSUE THREAD

**Issue by pdubeypublic571** [katzer/cordova-plugin-badge#119]
var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        this.receivedEvent('deviceready');
    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {

/*
**Focus here I have set it to 10 but still not able to see badge on app icon.**
*/
        cordova.plugins.notification.badge.set(10); // 

        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

app.initialize();

**Comment by GeekKorky** [comment]
Same here not working on Android 7.0

**Comment by katzer** [comment]
Please notice that the plugin only supports devices that are supported by ShortcutBadger. There's no error if its not possible to set a badge. The cordova plugin nor the underlying ShortcutBadger cannot know if its working or not because its not a core Android API.
