### ISSUE TITLE
Badges not working in background in iOS

### ISSUE THREAD

**Issue by JuanCAlpizar** [katzer/cordova-plugin-badge#12]
Hello, I'm using the badge plugin 0.5.2 version inside a phonegap build 3.3 application using jQuery mobile 1.4.2.

To keep the application running, I'm using the BackgroundJS plugin, which keeps the app in the background (to make sure it's working I added a popup inside a 5 minutes interval, which I can see after having the application minimized for that much time)

However the `window.plugin.notification.badge.set()`  doesn't seems to be working on background.

If I keep the app open I get the same popups and when I minimize it the application's icon has the badge number correctly applied.

If I minimize the app I never get the badge icon to update, even when I restore it back I get the popups, but when I minimize it back the icon still has no number change inside the badge.

Does the plugin requires the app to be open to upgrade the badges?

**Comment by desmondcain** [comment]
@katzer is this still true in v0.6.1? I'm running into the same issue on iOS8, Cordova v4.1.2, Ionic v1.3.8. I believe the OS allows some background processes to occur for at least a certain period of time. When minimizing the app, I've got notifications firing but the badge number won't increment; however, when the app is fully open and notifications fire, the badge number does increment.

Is there any way to allow badge numbers to update even when the app isn't in use?

**Comment by katzer** [comment]
To update badges in background or when the app isn't running you have two options: local-notifications or background plug-in.

**Comment by desmondcain** [comment]
Thanks for the quick reply and for pointing me in the right direction. Awesome work on all your plugins, as well!

**Comment by kashyapmukkamala** [comment]
Is there any update or different way to do this when is app is totally closed and not just in the background?

**Comment by boy008** [comment]
Hi @katzer 

Can you plz tell me, how can I  call the local-notifications or background plug-in  function in my app for badge number increase, when minimizing the app, I've got notifications firing but the badge number won't increment. But when I click the notification it's  increase.

I am used local-notifications below the code: 

$ionicPlatform.ready(function() {
cordova.plugins.notification.local.schedule({
    cordova.plugins.notification.badge.increase();
  })
})

Thank you.
