### ISSUE TITLE
Badge not display on app icon

### ISSUE THREAD

**Issue by JavaBoyHW** [katzer/cordova-plugin-badge#125]
I used ```shell cordova plugin add cordova-plugin-badge ``` add plugin to my project。Because my project in my server，so I copy D:\myproject\platforms\android\platform_www to my server。In badge.js，I insert "alert(“message”)" in ```exports.set``` function。```this.exec('set', args, callback, scope);``` run ，but no badge display on app icon。No Error log。
My environment is ：
Cordova version is 8.0.0；
Cordova-plugin-badge is the last；
Android phone is ：huawei KNT-AL 20，android 8.0.0。

**Comment by katzer** [comment]
Please notice, that the plugin only supports devices that are supported by ShortcutBadger. Huawei is partially supported. I have also Huawei and its also not working...
