### ISSUE TITLE
BADGE issues

### ISSUE THREAD

**Issue by stefanwilliam96** [katzer/cordova-plugin-badge#129]
i already use cordova cordova.plugins.notification.badge.set(10) and its work on phonegap, but didnt work in my xiaomi mi 2. Please help ... thanks

**Comment by stefanwilliam96** [comment]
i try from your test app for badge plugin, when i click support button, i got false ... what does it mean ?

**Comment by katzer** [comment]
Please see the other issues, there are many duplicates like yours. The plugin only supports devices supported by ShortcutBadger.

**Comment by stefanwilliam96** [comment]
> Please see the other issues, there are many duplicates like yours. The plugin only supports devices supported by ShortcutBadger.

i think you can try this plugin again because i already try this plugin in 4 different gadget (xiaomi mi 2, realme 2 pro, oppo a59, advan) and i still get not working plugin
