### ISSUE TITLE
Question : How to disable permission prompt on first App start ?

### ISSUE THREAD

**Issue by Aarbel** [katzer/cordova-plugin-badge#138]
Hi @katzer,

Is there a way to prevent the permission popup to be displayed on first App start ?
I want my users to validate later this kind of permission, with a better context.

It's also a required behavior (= don't show notifications permission popup on app launch) by Apple teams when they review the apps on the stores.

Thanks a lot for your help !

**Comment by katzer** [comment]
@Aarbel I dont have the popup on first app start (with latest plugin version)

**Comment by Aarbel** [comment]
Solved for me, i was trigerring setBadge in a bad way. Sorry for that.
