### ISSUE TITLE
Android Notifications

### ISSUE THREAD

**Issue by judins** [katzer/cordova-plugin-badge#20]
Hello everyone!
I have integrated plugin into android phonegap app, it works just fine in terms of sending Android notifications (in status bar), but does not show count on icon badge. I've reread code of plugin trying to find where this functionality is — but didn't find it and now I am wondering, how to make it work & integrate it properly? I may provide any additional information if needed.
Thank you in advance!

**Comment by Neotrixsx** [comment]
same issue for me .

**Comment by katzer** [comment]
hi, Android does not have icon badge numbers like iOS, instead it offers local notifications to display the badge number.

**Comment by judins** [comment]
Thank you
