### ISSUE TITLE
Badge not showing in Kitkat (4.4)

### ISSUE THREAD

**Issue by dominosoft** [katzer/cordova-plugin-badge#21]
Hi everyone, i'm using this plugin, when i set a new badge (with custom configuration) it show a message, just like a push notification, but the badge is not showing in the icon, do you have an idea why this happens? thanks!

**Comment by jimibi** [comment]
Hi,
On Android the badge will be displayed through a notification. See configure how to specify a custom notification title.

**Comment by dominosoft** [comment]
Hi, thanks for your response, i have reviewed the information about custom messages, but i can't find a way to use multiple lines in the message, in the 3rd image in the information about this plugin, shows a 2 line notification message, one with big font and the second line in smaller font, how can we accomplish this? and also what about the icon that can be used in the notification, can we use a custom icon? or just the icons that the OS provides, i found this list (androiddrawables.com) but not all icons are supported, any advice?

**Comment by PKnittel** [comment]
To create Toast-Notifications please use 

https://github.com/katzer/cordova-plugin-local-notifications
