### ISSUE TITLE
badge number not showing on android emulator and device

### ISSUE THREAD

**Issue by lanocturne** [katzer/cordova-plugin-badge#24]
Just tried the example by 'cordova emulate android' and 'ionic run android' on my device.

When click 'set 10' it does shows notifications on message center. However,  the badge number is not showing on home screen or app page's app icon.
![image](https://cloud.githubusercontent.com/assets/4869206/6884125/cddf65e4-d592-11e4-87ba-db6e23d2656f.png)

**Comment by mica16** [comment]
+1 same issue for me using a Samsung Galaxy S5

**Comment by katzer** [comment]
Yes sure - on Android app icons do not have badge numbers like in iOS

**Comment by lanocturne** [comment]
Thank you. Then how do Apps like Facebook and Pinterest have such a feature
on Android?

2015-03-30 11:52 GMT-07:00 Sebastián Katzer <notifications@github.com>:

> Yes sure - on Android app icons do not have badge numbers like in iOS
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/katzer/cordova-plugin-badge/issues/24#issuecomment-87789803>
> .
>



-- 
                   Sincerely,Stanislaus

**Comment by ggiacomo** [comment]
"Then how do Apps like Facebook and Pinterest have such a feature
on Android?" :+1:

**Comment by Duovili** [comment]
Have you got a conclusion about android???

**Comment by katzer** [comment]
They replace/manipulate the app's home icon

**Comment by Duovili** [comment]
I ran this yesterday on my device and its not showing at all.

On 22 April 2015 at 23:59, Sebastián Katzer <notifications@github.com>
wrote:

> They replace/manipulate the app's home icon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katzer/cordova-plugin-badge/issues/24#issuecomment-95351323>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by lanocturne** [comment]
@katzer Oh cool. Thank you for your guides.

**Comment by biocronic** [comment]
Same issue as lanocturne. There are badge numbers for samsung and android. all other apps display them on my phone. but not your test app. is there a way to do it? I use visual studio. Thank you for your support.

**Comment by katzer** [comment]
@lanocturne, @biocronic, see #3. I think the plugin could include the ShortcutBadger lib.

**Comment by Krishna25Vrinsoft** [comment]
@katzer Can you plz help me how i can use this lib in my project.
