### ISSUE TITLE
V 0.6.3 Phonegap Build Error

### ISSUE THREAD

**Issue by tmdevde** [katzer/cordova-plugin-badge#25]
HI,

i've just got this error while compiling with Phonegap Build on iOS:

The following build commands failed:
	CompileC build/xxx.build/Release-iphoneos/xxx.build/Objects-normal/armv7/APPBadge.o xxx/Plugins/de.appplant.cordova.plugin.badge/APPBadge.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Android is fine. I went back to 0.6.2 for now.

**Comment by DanailMinchev** [comment]
My build is also failed on Phonegap Build (iOS) and plugin version 0.6.3:
```
de.appplant.cordova.plugin.badge/APPBadge.m:158:25: error: use of undeclared identifier 'UIApplicationRegisterUserNotificationSettings'
                   name:UIApplicationRegisterUserNotificationSettings
```

**Comment by katzer** [comment]
Looks like PGB ignores the hook scripts...

**Comment by katzer** [comment]
Does anybody uses plugins with hooks (scripts) on PGB??

**Comment by abstractmatter** [comment]
Same here: use of undeclared identifier 'UIApplicationRegisterUserNotificationSettings'.
I'm not using any plugins with hooks :/

**Comment by bau720123** [comment]
+1

**Comment by bau720123** [comment]
hi all

I have been made a question to PGB
http://community.phonegap.com/nitobi/topics/-hook-scripts-problem
to see if there is any reply

**Comment by areijngoudt** [comment]
same here using Cordova

**Comment by antsav** [comment]
+1

**Comment by bau720123** [comment]
hi all and @katzer 
something update at here
http://community.phonegap.com/nitobi/topics/-hook-scripts-problem
https://github.com/phonegap/build/issues/425

but seem have no any help...

**Comment by katzer** [comment]
Finally Badge (v0.6.4), LocalNotification (v0.8.2dev) and PGB are compatible with each other

**Comment by reinos** [comment]
stil got problems with latest build of badge and localNotification together. Any idea?
