### ISSUE TITLE
Compilation issue With iOS

### ISSUE THREAD

**Issue by 1wQasdTeedFrsweXcs234saS56Scxs5423** [katzer/cordova-plugin-badge#30]
I am trying to use your plugin inside Phonegap/Cordova generated application. But the problem is it is not compiling when I run the iOS project.

/**
 * Register permission to show badges.
 *
 * @param callback
 *      The function to be exec as the callback
 */
- (void) registerPermission:(CDVInvokedUrlCommand *)command
{
    if (![[UIApplication sharedApplication]
         respondsToSelector:@selector(registerUserNotificationSettings:)])
    {
        return [self hasPermission:command];
    }

    _command = command;

    [self.commandDelegate runInBackground:^{
        [self.app registerPermissionToDisplayBadges];
    }];
}

#pragma mark -
#pragma mark Delegates

/**
 * Called on otification settings registration is completed.
 */
- (void) didRegisterUserNotificationSettings:(UIUserNotificationSettings*)settings
{
    if (_command)
    {
        [self hasPermission:_command];
        _command = NULL;
    }
}

![screen shot 2015-05-24 at 1 45 33 pm](https://cloud.githubusercontent.com/assets/7888138/7787194/29beb4ae-021c-11e5-8d1a-218c132391af.png)

**Comment by katzer** [comment]
Looks like somehow cordova has not installed the depend plugin __de.appplant.cordova.common.registerusernotificationsettings__
