### ISSUE TITLE
Badge always clears when tapping app icon

### ISSUE THREAD

**Issue by DURK** [katzer/cordova-plugin-badge#31]
Hi there,

It seems the badge gets cleared everytime I tap the app icon, even though I disabled this using (<a href="https://github.com/katzer/cordova-plugin-badge/wiki/05.-Clear-Badge#clear-the-badge-number-automatically-if-the-user-taps-on-the-app-icon">as stated here</a>):
```
cordova.plugins.notification.badge.configure({ autoClear: false });
```
Also the deprecated `cordova.plugins.notification.badge.setClearOnTap(false)` didn't have any effect.

Plugin version: 0.6.3 and 0.6.4.
iOS 8.3

Am I doing missing something, or is this a known issue? For now I've created a workaround that resets the badge to the last known value on Cordova's resume event.

**Comment by katzer** [comment]
@DURK, tested it today with 0.6.4 and 0.7.0dev and it was working for both iOS and Android.

**Comment by DURK** [comment]
@katzer I've tried 0.7.0dev but the same issue occurs. Do you mean your badge is not being cleared when resuming your app by clicking on the app icon?

**Comment by katzer** [comment]
@DURK, I am using the badge sample app and there it works. Badge gets cleared by clicking on the app icon depend on the _autoClear_ flag.

**Comment by dhaval-aspire** [comment]
Hey I also got this issue in ios 9.3.1, sample app is looks like dependent on older version(0.7.0) and also in that de.appplant.cordova.common.registerusernotificationsettings plugin deprecated.

**Comment by diegolmello** [comment]
Same issue here.
Version 0.7.2.

**Comment by clarklight** [comment]
Same, i want to disable the auto clear, tried cordova.plugins.notification.badge.configure({ autoClear: false }); but it isnt working. My badge still got cleared.

**Comment by gfitas** [comment]
Same problem with version 0.8.7

**Comment by ruizuikeda** [comment]
same v0.8.8

**Comment by lennertVanSever** [comment]
Same here
