### ISSUE TITLE
iOS question: Badge cleared when switching between apps with double click on home button

### ISSUE THREAD

**Issue by oddcb** [katzer/cordova-plugin-badge#32]
Hi, forgive me if this is the wrong place to ask. 

I'm having some trouble with using the plugin through ng-cordovas badge.js (https://github.com/driftyco/ng-cordova/blob/master/src/plugins/badge.js) in an ionic app.

On cordovas resume event I trigger the bagde update (from my app.js file): 

Typescript:
```typescript
    .run("$timeout", "$ionicPlatform", "$cordovaBadge", "BadgeCounterService", "TaskResource", ($timeOut:ng.ITimeoutService, $ionicPlatform:ionic.IonicPlatform, $cordovaBadge:ngcordova.Badge, badgeCounterService:ft.badge.BadgeCounterService, taskResource:ft.resources.TaskResource) => {
        $ionicPlatform.on("resume", () => {
            console.log("Resuming app");
            taskResource.getTaskCount((taskCount:l.TaskCount) => {
                // Without timeout here, of at least 500ms the badge won't be set through the service even on single tap of home button.. for some reason.
                $timeOut(() => {
                    badgeCounterService.updateTaskCount(taskCount:l.TaskCount);
                }, 500, false);
            });
        });
    }])
```

The badgeCounterService impl: 

Typescript:
```typescript
public updateTaskCount(num:number):void {
  this.$cordovaBadge.set(num);
  this.taskCount = num;
}
```

So the above two code snippets code work (with the exception that I have to set a timeout) when the user normally presses their home button once and goes i and out of the app. The problem occours when the user double taps and switches to e.g. Safari and then double taps back to the app. The count is retrieved and the bagde is updated correctly inside the app, but is not set on the icon on the home screen. 

I've also tried to simplify the code (it's still from ionics run method though): 

Typescript:
```typescript
document.addEventListener("deviceready", ()=> {
    var config = setTimeout(() => $cordovaBadge.configure({autoClear: false}), 0);
    console.log("Config: ", config);
}, false);

document.addEventListener("resume", () => {
    $cordovaBadge.set(100).then(() => {
            $cordovaBadge.get().then((num) => {
                console.log("number on homescreen: ", num)
            })
        });
}, false)
```

But still no luck. In this case, without the timeout, the badge number is not set on home screen at all. The console log of badge number on homescreen is also inconsistent: 

```
2015-06-02 10:49:50.354 app[1147:111758] number on homescreen:  100
2015-06-02 10:49:50.785 app[1147:111758] active
2015-06-02 10:49:52.576 app[1147:111758] number on homescreen:  100
2015-06-02 10:49:52.970 app[1147:111758] active
2015-06-02 10:49:55.058 app[1147:111758] number on homescreen:  0
2015-06-02 10:49:55.474 app[1147:111758] active
2015-06-02 10:49:57.207 app[1147:111758] number on homescreen:  100
2015-06-02 10:49:57.630 app[1147:111758] active
2015-06-02 10:50:06.227 app[1147:111758] number on homescreen:  0
2015-06-02 10:50:06.517 app[1147:111758] active
2015-06-02 10:50:17.075 app[1147:111758] number on homescreen:  0
2015-06-02 10:50:17.350 app[1147:111758] active
2015-06-02 10:50:19.965 app[1147:111758] number on homescreen:  100
2015-06-02 10:50:20.387 app[1147:111758] active
```
Log statement for config reports that autoClear is set to false. Any thoughts?

**Comment by lookitsatravis** [comment]
I'm also having this problem and would appreciate an answer.

**Comment by katzer** [comment]
@oddcb, please retry with 0.7.0dev. I have added callback support for `set` and `clear`, ...
Using them solved your problem for me.
