### ISSUE TITLE
Android question: The badge comes as notification instead of a badge

### ISSUE THREAD

**Issue by nesh170** [katzer/cordova-plugin-badge#34]
```javascript
var androidBadge = cordova.plugins.notification.badge;
androidBadge.configure({ smallIcon: 'icon' });
androidBadge.set(6);
```

I use this when messages come in. And instead of showing 6 as a badge icon. It shows it as a notification. '6 new messages'.

I am testing on a HTC One M7

Thanks

**Comment by nesh170** [comment]
I was reading up on App notifications. I believe that HTC does not support badge notification and it isn't part of Android's design language. 
Would this be true?

Thanks

**Comment by meer-online** [comment]
facing the same issue, the message '1 new message' shows up as notification instead of the badge. Tested on Samsung galaxy series with Android 5.0

is there anything specific configuration/setting that needs to be done to show it as badge instead of notification?

**Comment by nesh170** [comment]
@meer-online I found out that it depends on your phone. TouchWiz (Samsung) has support for badges so it works while the HTC One does not so it doesn't show any badges

**Comment by barryvdh** [comment]
Soo, it's not possible?

On my HTC One M8, Whatsapp does show a badge..

**Comment by barryvdh** [comment]
See this SO answer: http://stackoverflow.com/a/25849212/444215

So it should be possible on Samsung/HTC/LG devices..

**Comment by katzer** [comment]
The plugin does show badges wherever ShortcutBadger says its able to do that, otherwise it displays the notification as before.
