### ISSUE TITLE
Android build is not working anymore

### ISSUE THREAD

**Issue by ispieter** [katzer/cordova-plugin-badge#35]
Hello Katzer,

I've updated your plugin and it seems that i can't build my app anymore.
I'm receiving the following error:

```/platforms/android/src/de/appplant/cordova/plugin/badge/LaunchActivity.java:32: Error: This class should be public (de.appplant.cordova.plugin.badge.LaunchActivity) [Instantiatable]```

It looks like it's because of the changes in c123e8f75b5ab4e9a704e581b04d0758fba2dbb1

**Comment by katzer** [comment]
Thanks!
