### ISSUE TITLE
Build doest not work (intel xdk)

### ISSUE THREAD

**Issue by firefrogz** [katzer/cordova-plugin-badge#36]
Hi,
since your last update i' facing a build error but i don't have logs to show you.
the build error only appears on Android build, not IOS.
the problem appears since the update badge for android : 
Support for app icon badges on selective Android platforms
thanks in advance :)

The build failed. An error occurred while building the application. Verify your build assets are correct and try again.
Build Log:
Building a Cordova 4.1.2 application.
The application name is "Clara-M"
The package name is "com.eurofirstmultimedia.claram"
Preference android-signed set to false. Application will not be signed.
Plugin "org.apache.cordova.device" (0.2.13) installed.
Plugin "org.apache.cordova.splashscreen" (0.3.5) installed.
Plugin "org.apache.cordova.contacts" (0.2.15) installed.
Plugin "org.apache.cordova.file" (1.3.2) installed.
Plugin "org.apache.cordova.file-transfer" (0.4.8) installed.
Plugin "org.apache.cordova.geolocation" (0.3.11) installed.
Plugin "org.apache.cordova.globalization" (0.3.3) installed.
Plugin "org.apache.cordova.inappbrowser" (0.5.4) installed.
Plugin "org.apache.cordova.dialogs" (0.2.11) installed.
Plugin "org.apache.cordova.vibration" (0.3.12) installed.
Plugin "org.apache.cordova.statusbar" (0.1.9) installed.
Plugin "com.intel.xdk.file" (1.0.1) installed.
Plugin "com.intel.xdk.device" (1.0.7) installed.
Plugin "org.apache.cordova.camera" (0.3.4) installed.
Plugin "org.apache.cordova.media-capture" (0.3.5) installed.
Plugin "org.apache.cordova.network-information" (0.2.14) installed.
Plugin "nl.x-services.plugins.socialsharing" (4.3.19) installed.
Plugin "com.phonegap.plugins.facebookconnect" (0.10.1) installed.
Plugin "com.phonegap.plugins.PushPlugin" (2.4.0) installed.
Plugin "cc.fovea.cordova.purchase" (3.11.0) installed.

**Comment by firefrogz** [comment]
After some inverstivations the build error appears when adding this line : 
<framework src="src/android/badge.gradle" custom="true" type="gradleReference"/>

**Comment by katzer** [comment]
I have corrected the engine requirements. You need to update plugman.
