### ISSUE TITLE
PGB limited to version 0.6.4

### ISSUE THREAD

**Issue by JGLiv** [katzer/cordova-plugin-badge#39]
For some reason the version on PhoneGap Build is stuck on 0.6.4 and isn't updating to 0.7.1. Is this something you can fix?

**Comment by BUATHERA** [comment]
Also having the same problem. it just keeps pulling v0.6.4...would love to know if there is a fix..!!

**Comment by katzer** [comment]
Its not yet published on PGB. Adobe requires charges to upload plugin updates.

**Comment by BUATHERA** [comment]
Thanks sebastian,
for clarifying. Looking forward to it though. I love the badging feature
for the selected android devices..v0.6.4 does not badge my app icon on my
Sumsung S4 ( Android 4.4.2). Am counting on v0.7.1..

**Comment by bau720123** [comment]
hi @katzer 
also we can install the nom from in PGB
```
<gap:plugin name="de.appplant.cordova.plugin.badge" source="npm" version="0.7.1" />
```
but it will cause only Android build fail (ios and wp are build success)

**Comment by bau720123** [comment]
hi @katzer 
any idea ?

**Comment by bau720123** [comment]
hi @katzer 
0.7.0 verison work for PGB
but 0.7.1 not (it will build fail)

**Comment by katzer** [comment]
@JGLiv Uploading plugins on PBG isnt possible anymore in favor of npm.

```xml
<gap:plugin name="de.appplant.cordova.plugin.badge" source="npm" />
```

**Comment by bau720123** [comment]
hi @katzer 
confirmed and thanks for that
```
<plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />
```
