### ISSUE TITLE
Doesn't work in debug?

### ISSUE THREAD

**Issue by ethode** [katzer/cordova-plugin-badge#44]
I am testing this out on iOS using the PhoneGap debug application.  After hitting phonegap serve and loading up in the iPhone, I get my "deviceready" event and I trigger an alert just to get a popup of when this event triggers, I then run: 

`cordova.plugins.notification.badge.set(10);`

After checking the badge in iOS there is not number at all present no less a 10.
I have no errors output on the terminal screen.

Thanks in advanced, great plugin concept!

**Comment by bau720123** [comment]
same here
https://github.com/katzer/cordova-plugin-badge/issues/43

**Comment by katzer** [comment]
Closing since its duplicated.

@ethode Did you found out the reason?
