### ISSUE TITLE
0.7.1 version from npm will cause PGB ios build fail

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-badge#45]
hi @katzer 
I am using PGB cli-5.2.0 + gradle build
for now 0.7.1 version from npm will cause PGB ios build fail and have these error message
```
Error - The following plugin (or plugin version) is not on npm or not available for this platform:
de.appplant.cordova.plugin.badge@0.7.1": Fetching plugin "de.appplant.cordova.plugin.badge@0.7.1" 
via npm Installing "de.appplant.cordova.plugin.badge" for ios Fetching plugin
"de.appplant.cordova.common.registerusernotificationsettings
```

**Comment by bau720123** [comment]
hi @katzer 
all detail at here
http://community.phonegap.com/nitobi/topics/-only-ios-error-the-following-plugin-or-plugin-version-is-not-on-npm-de-appplant-cordova-plugin-badge-0?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply[id]=16294111#reply_16294111

**Comment by katzer** [comment]
@bau720123 OK, is fixed now with 0.7.2

**Comment by bau720123** [comment]
hi @katzer 
confirmed and thanks for that
```
<plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />
```

**Comment by GiladAdar** [comment]
Hi,
this <plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" /> 
worked for me for ios phonegap remote build but not for android, 
and idea why?
