### ISSUE TITLE
The badge is not showing when I remove/add platform android

### ISSUE THREAD

**Issue by nostub** [katzer/cordova-plugin-badge#46]
Hello,
When I build the android application from cordova-plugin-badge-example, the badge is showing correctly on the icon (I have a samsung galaxy Note II). But when I do:
"cordova platform remove android"
"cordova platform add android"
"cordova run android"
The badge is not showing anymore after that (for information, I need to tape these commands to install correctly a notification push plugin).
Any idea to how correct this problem?

Thanks in advance!

**Comment by katzer** [comment]
@nostub Sometimes "cordova build android" helps
