### ISSUE TITLE
android studio gradle app execution failed for task ':prepareMeLeolinShortcutBadger112Library'.

### ISSUE THREAD

**Issue by hare2011** [katzer/cordova-plugin-badge#49]
when i install this plugin ,gradle app throw the error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareMeLeolinShortcutBadger112Library'.
> Could not expand ZIP '/Users/hare/.gradle/caches/modules-2/files-2.1/me.leolin/ShortcutBadger/1.1.2/80367deac58e3730ea374f524ea3b927aa8fdaec/ShortcutBadger-1.1.2.aar'.

How  can i solve it

**Comment by katzer** [comment]
Maybe a temp. issue but seems like not an issue of the plugin itself.
