### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by satya5561** [katzer/cordova-plugin-badge#50]
Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.1, failed version requirement: >=4

**Comment by mix3d** [comment]
This error says your Android cordova platform version is too old, and doesn't meet the plugin requirements.

You need to update your Cordova version, and subsequently your android platform to the latest version. 
Assuming Linux/OSX, run `sudo npm update -g cordova` to get the latest versions, then `cordova platform update android`

Alternatively, request an older version of the plugin that supports the android platform 3.7.1. (using the `cordova plugin add de.appplant.cordova.plugin.badge@VERSION.NUMBER.BUILD` format, like @3.2.2, for a version of this plugin that is compatible with the older Android platform)
