### ISSUE TITLE
Remove dependency on de.appplant.cordova.common.registerusernotificationsettings

### ISSUE THREAD

**Issue by adhipg** [katzer/cordova-plugin-badge#51]
I believe that `cordova-plugin-app-event` is the preferred choice for this functionality now.

Currently the latest versions of `cordova-plugin-badge` and `cordova-plugin-local-notifications` can't be used in the same project since the same dependencies are defined by two different packages.

**Comment by bau720123** [comment]
agree with @adhipg

**Comment by gdagley** [comment]
It looks like @adhipg https://github.com/adhipg/cordova-plugin-badge got it working with minimal changes.

using 
```
cordova plugin add --save https://github.com/adhipg/cordova-plugin-badge
```

or putting this in your config.xml will get that fork of the `cordova-plugin-badge`

```
  <plugin name="de.appplant.cordova.plugin.badge" spec="https://github.com/adhipg/cordova-plugin-badge" />
```

**Comment by dam1** [comment]
Thanks @adhipg !
