### ISSUE TITLE
Not showing badge on android.

### ISSUE THREAD

**Issue by dspjm** [katzer/cordova-plugin-badge#52]
I executed:
`cordova.plugins.notification.badge.set(10)`

There is a notification showing but no badge on the app icon. I am running Android 5.1.1 (API level 22)
![screenshot from 2016-01-15 11 44 43](https://cloud.githubusercontent.com/assets/3742673/12345019/9e9dccd0-bb7e-11e5-9db6-a4134559e4d4.png)

**Comment by katzer** [comment]
@dspjm With 0.7.2 the plugin on Android wraps the ShortcutBadger lib to display app icons. Before it was using notifications as shown on your picture.
