### ISSUE TITLE
not building with cordova-ios 4.0.1

### ISSUE THREAD

**Issue by bau720123** [katzer/cordova-plugin-badge#54]
all detail right here
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/27
this is why "de.appplant.cordova.plugin.badge" the error occur is

developer should be follow this in iOS@4.0.1
http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html

**Comment by katzer** [comment]
@bau720123 I've tested 0.7.2-dev with iOS@latest (4.0.1) with & without wkwebview-engine and it works - build succeeded.

**Comment by bau720123** [comment]
hi @katzer 
confirmed and thanks for that
```
<plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />
```
