### ISSUE TITLE
clear badge

### ISSUE THREAD

**Issue by kahunafr** [katzer/cordova-plugin-badge#55]
Hi
After opening the application, the badges will not empty. They always increment.
The badge disappears when opening the application, but when next push the badge appears incremented.
Is there a solution?

**Comment by katzer** [comment]
@kahunafr Can you explain what you mean and also with "next push".

**Comment by HowieSheng** [comment]
I think I have the same problem. For example, at the beginning the badge number is 5. I called clear() function to remove the badge successfully. But once next push notification arrived, the badge number appeared to be 6 not 1 that I expected.

**Comment by rodrigo01** [comment]
do you use increment ? or SET?

**Comment by katzer** [comment]
I cannot reproduce
