### ISSUE TITLE
Make notification on Android optional when badge not supported

### ISSUE THREAD

**Issue by robinbonnes** [katzer/cordova-plugin-badge#56]
Hello,

First of all great work!

Is it possible to make the notification on Android optional? For my app I only want to place a badge on new content in the application, but I don't want to show a notification instead of showing an icon badge  if this is not supported.

Regards,

Robin

**Comment by katzer** [comment]
@robinbonnes With version >= 0.7.2 the plugin on Android is only using the ShortcutBadger lib. The former local-notifications fallback has been removed.
