### ISSUE TITLE
Error: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.

### ISSUE THREAD

**Issue by spi7fire** [katzer/cordova-plugin-badge#57]
every time i install on my mac this plugin for iOS i get this error:

cordova plugin add https://github.com/katzer/cordova-plugin-badge.git 

/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add https://github.com/katzer/cordova-plugin-badge.git ":
Fetching plugin "https://github.com/katzer/cordova-plugin-badge.git" via git clone
Repository "https://github.com/katzer/cordova-plugin-badge.git" checked out to git ref "master".
Installing "de.appplant.cordova.plugin.badge" for ios
Fetching plugin "de.appplant.cordova.common.registerusernotificationsettings" via npm
Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:146:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Error: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings

**Comment by barryvdh** [comment]
I have the same issue.

**Comment by spi7fire** [comment]
i've removed the badge plugin from my code, it made too many problems.. its dependencies aren't stable enough for production, and make lot of bad access crush conflicts with other plugins (such as camera plugin).

**Comment by barryvdh** [comment]
So what's the alternative for Android badges?

**Comment by ispieter** [comment]
That library seems to be deprecated and soon replaced by https://github.com/katzer/cordova-plugin-app-event.

When can we expect this, @katzer?

**Comment by ispieter** [comment]
https://github.com/katzer/cordova-plugin-badge/pull/53
A pull request regarding this issue is ready to be merged.

**Comment by katzer** [comment]
@spi7fire, @ispieter See 7542fa3 and #53 - Thanks!

**Comment by alaskSoft** [comment]
Warning: Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
