### ISSUE TITLE
How to set the badge with a new notification

### ISSUE THREAD

**Issue by martinr77** [katzer/cordova-plugin-badge#59]
I've read your docs and I want to know if it is possible to set the badge count without starting the app. If there comes in a notification, is it possible to set the badge directly?

**Comment by shawns582** [comment]
also wondering about this.  thanks

**Comment by badpenguin** [comment]
push notifications can do this, you need a different plugin

**Comment by katzer** [comment]
@martinr77 Thats possible via LocalNotification and PushNotification API.
