### ISSUE TITLE
0.7.2 on npmjs.com ?

### ISSUE THREAD

**Issue by badpenguin** [katzer/cordova-plugin-badge#60]
When 0.7.2 will be available on npmjs.com?

I've problem with 0.7.1 crashing on IOS.

**Comment by bau720123** [comment]
hi @badpenguin 
well...
you should try to search it by yourself
https://www.npmjs.com/package/cordova-plugin-badge

**Comment by badpenguin** [comment]
nevermind... i found the problem was a conflict with another plugin
