### ISSUE TITLE
integration with phonegap-plugin-push when on background

### ISSUE THREAD

**Issue by parismav87** [katzer/cordova-plugin-badge#62]
Hello, 
I would like to know if there is a way to change the badge number when the app has been closed or still runs at the background (for android). 
```
push.on('notification', function(data) {
			console.log(data);
			if(!data.additionalData.foreground)
        	{
        		cordova.plugins.notification.badge.set(10);
        		
        	}
}
```

The above code doesn't seem to trigger the badge.set function. 
I have tried to work with the phonegap-plugin-background-mode but I saw some people having issues with the Appstore, so I rejected that option. 
Could you guide me on how to do this? All I want is to be able to change the badge number when the app is not on the foreground.
Regards

**Comment by ilvalerione** [comment]
+1

**Comment by parismav87** [comment]
@ilvalerione  + any1 else interested, I got an answer from the cordova-plugin-push thread-> https://github.com/phonegap/phonegap-plugin-push/issues/190#issuecomment-203458757 
Said that by the end of April, changing the badge number through that plugin is going to be available for Android.

**Comment by ilvalerione** [comment]
@parismav87  thanks so much!

**Comment by mlabarca** [comment]
In case anyone is following this, the phonegap-plugin-push just updated yesterday with code to set badges on android: https://github.com/phonegap/phonegap-plugin-push/blob/master/CHANGELOG.md

**Comment by parismav87** [comment]
Thanks @mlabarca !
