### ISSUE TITLE
A plugin in your app does not support the compulsory arm64 (64-bit support) architecture

### ISSUE THREAD

**Issue by reinos** [katzer/cordova-plugin-badge#63]
I get this error when building Badge V0.7.2 and LocalNotification V0.8.4

Any idea?

related to #25 ?

**Comment by rodrigo01** [comment]
i use this try:
#config.xml
<preference name="android-build-tool" value="gradle" />
  <plugin name="de.appplant.cordova.plugin.local-notification" />
  <plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />

**Comment by andersborgabiro** [comment]
I get this error when stating spec="0.7.2". Removing this plugin also removes the error.

Any ideas?

Cheers,
Anders
