### ISSUE TITLE
Cannot stop the badge from displaying

### ISSUE THREAD

**Issue by pithhelmet8669** [katzer/cordova-plugin-badge#64]
Hello -  using version 0.6.4 under phonegap.  I added the plugin, and got it to display a 1 in the badge, even though i told it to print a 10, it only displays a 1.

using this code block....
cordova.plugins.notification.badge.set(1);

Now, I have removed all references to the plug in, verified that it is not being loaded in phonegap, but the application is still showing a 1 (one) as the badge.

I have removed the application from my ipad, and loaded the fresh build (without the plugin) and it still shows a one as the badge on a new device.

There are two parts - 
1) Why is the badge still showing - even though i have pulled it out of the code?
2) Why is it only showing a one on the badge, even though i told it to display a 10.

thank you
tony

**Comment by rodrigo01** [comment]
What OS version do you use?

**Comment by firmanhidayat** [comment]
yes. It same with mine. badge cant stop displaying from my iPhone iOs 9.3.2

**Comment by pithhelmet8669** [comment]
i finally gave up and removed the plug in.

**Comment by firmanhidayat** [comment]
Yes do the same with me, I removed it. But badge is still displaying until now.

**Comment by katzer** [comment]
Please don't use the hosted plugin version on PBG and switch to NPM!
