### ISSUE TITLE
Phonegap build cannot find package shortcutbadger

### ISSUE THREAD

**Issue by smarbos** [katzer/cordova-plugin-badge#68]
Hello, im tryng to compile my app with phonegap and this fails.

Import in config.xml looks like:
`<plugin name="cordova-plugin-badge" spec="https://github.com/katzer/cordova-plugin-badge.git" />
`

> -compile:
>     [javac] Compiling 24 source files to /project/bin/classes
>     [javac] /project/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:33: error: package me.leolin.shortcutbadger does not exist
>     [javac] import me.leolin.shortcutbadger.ShortcutBadger;
>     [javac]                                ^
>     [javac] /project/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:53: error: cannot find symbol
>     [javac]         ShortcutBadger.removeCount(ctx);
>     [javac]         ^
>     [javac]   symbol:   variable ShortcutBadger
>     [javac]   location: class BadgeImpl
>     [javac] /project/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:86: error: cannot find symbol
>     [javac]         ShortcutBadger.applyCount(ctx, badge);
>     [javac]         ^
>     [javac]   symbol:   variable ShortcutBadger
>     [javac]   location: class BadgeImpl

Thanks for your time, if you need more info, please let me know!

**Comment by rodrigo01** [comment]
use this
 < plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />

**Comment by Criccle** [comment]
Hi guys, I'm curious to hear if this fixed the issue for you. I am running into the exact same error and the different form of importing didn't help.

**Comment by avaiskhatri** [comment]
Hey guys, I am having the same issue. Did any one have found any solution ?

**Comment by clarklight** [comment]
Yer it doesnt work for me as well

**Comment by katzer** [comment]
If you're using PhoneGap Build please make sure you specify grade as your Android build tool in config.xml: 
```xml
<preference name="android-build-tool" value="cradle" />
```
