### ISSUE TITLE
Warning: Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.

### ISSUE THREAD

**Issue by alaskSoft** [katzer/cordova-plugin-badge#70]
I use telerik, so i have to use the Version 0.7.1, but it is not possible to install the plugin because of the error:

Warning: Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry. Same Error as   in #57

**Comment by Lecramed** [comment]
I have the same issue, please help

**Comment by alaskSoft** [comment]
I received an answer from telerik. They prepared version 0.72 of the plugin. It solved the problem.

**Comment by Lecramed** [comment]
Great! Thank you
