### ISSUE TITLE
not showing

### ISSUE THREAD

**Issue by zanurano** [katzer/cordova-plugin-badge#72]
not showing badge in android. but if run in browser it's work.
why?

**Comment by JohannesHoffmann** [comment]
+1 also not working :(

**Comment by Anopetia** [comment]
+1 same here, but this works on iOS.

**Comment by clarklight** [comment]
+1 Same its not working on Android

**Comment by Krishna25Vrinsoft** [comment]
+1 same for me. I am very confuse. it's not working on Android

**Comment by itemir** [comment]
Check #69

**Comment by katzer** [comment]
The plugin supports all devices and OSes supported through ShortcutBadger!
