### ISSUE TITLE
Badge number is not display in Android

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [katzer/cordova-plugin-badge#74]
I am trying to run this app in android but count number is not display in android. I can see notification but can't display count number. Can anyone please help me. I want to display count in App icon .

**Comment by itemir** [comment]
I am seeing the same.

**Comment by drsatan1** [comment]
It doesn't work in the stock Android launcher, please read.

**Comment by katzer** [comment]
@Krishna25Vrinsoft If you cannot see the badge then its not supported via ShortcutBadger, e.g not support by your Android OS.
