### ISSUE TITLE
Its not working in Android?

### ISSUE THREAD

**Issue by shafinmsalim** [katzer/cordova-plugin-badge#75]
I can install it successfully on ios, but in android its not working. 

First I install cordova-plugin-badge@0.7.2 version but it needs cordova-android@>=4 version. Then update android and install badge then cordova build shows error.

Then i install cordova-plugin-badge@0.7.1 and build cordova. But there is no badge shown in the app.

Also try ShortcutBadger by adding mavenCentral to the build script.

Please give me a solution

**Comment by shafinmsalim** [comment]
anyone pls giv a solution

**Comment by shafinmsalim** [comment]
anyone pls giv a solution

**Comment by shafinmsalim** [comment]
anyone pls giv a solution

**Comment by itemir** [comment]
I am seeing a similar behavior. Are there specific set of instructions for Android? It works just fine on iOS.

**Comment by ebuyuk** [comment]
Hi,
First I tried with Insignia tablet and do not work. I tried in Samsung and It works(Android 6.0.1).Only some devices could support.I saw comment in this issue.
https://github.com/phonegap/phonegap-plugin-push/issues/190

**Comment by andersborgabiro** [comment]
For me: Works on Android 5.0.1, but not 6.0.1.

Is this really device rather than Android version dependent? It shouldn't be.

**Comment by katzer** [comment]
Badging the app icon isn't supported on Android by native. It depend on the manufacturer.
