### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by al922001** [katzer/cordova-plugin-badge#76]
Hi there, I tested this plugin on 3 Sony xperia (Z, Z3 & Z5) and Samsung galaxy S4 but it doesn't work at all. The 0.7.1 version work for my xperia Z but only with badges not notifications.

**Comment by andreszs** [comment]
**I can confirm that version 0.7.3 does not work at all, badge is not updated nor cleared by any means.**

Luckily I was able to restore version 0.7.2 from a backup, which works perfectly.

**Comment by katzer** [comment]
@al922001, @andreszs Might be best to open a ticket here because of the plugin uses the lib.
https://github.com/leolin310148/ShortcutBadger

I've tested with Samsung and Simulator with NOVA launcher without problems. See #79.
