### ISSUE TITLE
Cannot read property 'notification' of undefined when building phonegap app with angular

### ISSUE THREAD

**Issue by GianlucaCesari** [katzer/cordova-plugin-badge#77]
Hello, I added the plugin via 
`cordova plugin add cordova-plugin-badge`
and then tried to use it inside my angular controller like this: 

``` javascript
s.selectTimer = function(event) { 
   //some code here
   window.plugin.notification.badge.set(10);
}
```

But in the console i see something like this: 

```
Cannot read property 'notification' of undefined at m.s.selectTimer
```

Is there something I'm doing wrong? 

edit: im using phonegap serve and/or cordova run ios --device

**Comment by SamTinchern** [comment]
Holle！I also had this problem, Can I learning for you?

**Comment by katzer** [comment]
@GianlucaCesari Seems like the plugin isnt installed properly. Try `cordova build ios` to fix it.

**Comment by katzer** [comment]
BTW the preferred namespace is `cordova.plugins.notification.badge`
