### ISSUE TITLE
How to stop IOS auto clear??

### ISSUE THREAD

**Issue by clarklight** [katzer/cordova-plugin-badge#78]
On resume, the badge got cleared on IOS, is there a way to stop that? I want to keep the badge number and clear manually

**Comment by adam187** [comment]
@clarklight I don't think it's this plugin fault that your badge is being cleared on resume. 

I had same issue and it tuned out that other plugin https://github.com/OneSignal/OneSignal-Cordova-SDK that was clearing bade.

**Comment by katzer** [comment]
@clarklight That's handled by the OS internally.
