### ISSUE TITLE
Phone Gap Build. Failed to install 'de.appplant.cordova.plugin.badge'

### ISSUE THREAD

**Issue by randres61** [katzer/cordova-plugin-badge#80]
I want to build my app using Phonegap builder (build.phonegap.com). I have added in this release your plugin "cordova-plugin-badge" and build for IOS but it's failing.

In log appears the next error:

> Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.

My config.xml which I have attached in .zip format,  contains the next  following xml, because I want to use the latest version of the plugin:

<gap:plugin name="de.appplant.cordova.plugin.badge" source="npm" />

What's wrong?

If I use:
<plugin name="de.appplant.cordova.plugin.badge" spec="0.6.4" source="pgb" />
all goes OK, but as you know "pgb" source will be removed next 15/11, and I need to use "npm" source.

Could you help 
[config.zip](https://github.com/katzer/cordova-plugin-badge/files/587706/config.zip)
me?
Thanks for all and if you might need more information please tell me.

**Comment by katzer** [comment]
@randres61,

Use the new plugin-id (since v.0.7.2)

```xml
<gap:plugin name="cordova-plugin-badge" source="npm" />
```

**Comment by randres61** [comment]
Sorry, for my late answered, and thanks for all
