### ISSUE TITLE
IsBadgeWorking.Android ok, but not cordova-plugin-badge (android 6.0)

### ISSUE THREAD

**Issue by yelban** [katzer/cordova-plugin-badge#81]
the ShortcutBadger demo app "IsBadgeWorking" is working on Sony Z3 ( android 6.0.1 0 without any problem.
but not cordova-plugin-badge even use  ShortcutBadger@1.1.11

https://github.com/leolin310148/IsBadgeWorking.Android

**Comment by katzer** [comment]
@yelban the badge plugin v0.7.3 uses ShortcutBadger@1.1.8. The recent released v0.7.4 uses the latest ShortcutBadger@1.1.11

**Comment by katzer** [comment]
As I have no Android 6, does it work now with cordova-plugin-badge@0.7.4?

**Comment by yelban** [comment]
No, cordova-plugin-badge@0.7.4 is not work on Sony Xperia Z3 - Android 6.0.1

**Comment by katzer** [comment]
@yelban See #79. Closing this ticket as both describe the same issue.
