### ISSUE TITLE
Badge Count Not Working on all Android devices

### ISSUE THREAD

**Issue by siddharthnaik7** [katzer/cordova-plugin-badge#82]
Hi, 

I tried using this plugin, with `cordova.plugins.notification.badge.set(10);`
For me It is working only on Samsung Note 3 Neo (Android 5.1.1), and not any other Android devices.
Also, I tried using: https://github.com/leolin310148/IsBadgeWorking 
But I am unable to use this library in Ionic.
Kindly, let me know how can we get the Badge count on most of the Android devices.

Thanks - Sid

**Comment by katzer** [comment]
@siddharthnaik7 Please see the other open issues first: #79 

The plugin uses [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) (the latest version) to visualise unread badges. If your launcher/device isn't supported then please open a request there.

Thanks.

BTW It's not true that it's not working on all devices...
