### ISSUE TITLE
how to badge increase when the application isn’t running in the foreground.

### ISSUE THREAD

**Issue by madara134** [katzer/cordova-plugin-badge#85]
i use notification in phonegap but it not auto increase when receive notification. 
      push.on('notification', data => {
         let page = data.additionalData.page;
         let id = data.additionalData.id;
         if (!data.additionalData.foreground) {
        this.platform.ready()
          .then(() => {
            this.platform.pause.subscribe(() => {
              Badge.increase(1)
            })
            if (!this.modal) {
              this.modal = this.modalCtrl.create(this.pages[page].pagechild, { id: id });
              this.modal.present()
                .then(() => {
                  Badge.clear();
                  Badge.set(0);
                  this.content.insert(1, this.pages[page].component)
                })
            }
          })
      }

**Comment by katzer** [comment]
@madara134 The app itself can't change the badge if its not running. You may use the background-mode plugin to do so while in background or by remote notifications if not running.
