### ISSUE TITLE
Unable to take build in intel xdk using this plugin

### ISSUE THREAD

**Issue by asnmsd** [katzer/cordova-plugin-badge#86]
Hi,
I used this plugin to take build using Intel xdk and got and error:

Error: Plugin Badges cannot be added. The plugin contains Gradle scripts.

Any solution like editing the gradle?

**Comment by katzer** [comment]
@asnmsd Then you may need to wait until Intel XDK supports gradle scripts. The build scripts is required to add dependencies.
