### ISSUE TITLE
Badge gets cleared by local notification

### ISSUE THREAD

**Issue by ammichael** [katzer/cordova-plugin-badge#87]
Hi there!

First, I feel I need to thank you for all your plugins. I'm using three of them; my apps wouldn't exist if it wasn't for these plugins (:

I just reached a strange situation, which I searched for an issue here and in local notification plugin issues, but couldn't find an answer.

I'm setting the badge of the app, and also scheduling notifications. When I receive the notification, it is automatically cleared, since the notification was schedule with no `badge` property. 

Is it the intended behavior? Maybe I can set properly the badge values in the notifications, but I rather keep things the way they are right now; controlling badges with badge plugin, notifications with notification plugin.

Thanks

**Comment by katzer** [comment]
@ammichael I see. That need to be done on local-notification side. About what platform are you talking, Android? iOS?

**Comment by ammichael** [comment]
@katzer on iOS. Didn't try on Android

**Comment by katzer** [comment]
@ammichael Should be fixed with next version of local-notification plugin.
katzer/cordova-plugin-local-notifications@8767a0f264060a47dc6449dc5857bebe58d61e2e

**Comment by ammichael** [comment]
That's awesome! Thanks @katzer (:
