### ISSUE TITLE
Problem building Sample App

### ISSUE THREAD

**Issue by djtruco** [katzer/cordova-plugin-badge#89]
Hello everyone,

First of all, thanks @katzer for your great help with this plugins! 

I'm trying to build the Sample App I cloned as suggested:
`git clone -b example https://github.com/katzer/cordova-plugin-badge.git`

The first problem is the plugin is a symbolic link to a folder in Sebastian's file system:
![image](https://cloud.githubusercontent.com/assets/3768482/23914260/6e9119a6-08b3-11e7-9a97-75a412e901d6.png)

So I removed the symbolic link and installed the plugin as suggested:
`cordova plugin add https://github.com/katzer/cordova-plugin-badge.git`

After that I found out other problems with symbolic links for this files:
```
cordova-plugin-badge/platforms/android/cordova-plugin-badge/example-badge.gradle
cordova-plugin-badge/platforms/android/src/de/appplant/cordova/plugin/badge/Badge.java
cordova-plugin-badge/platforms/android/src/de/appplant/cordova/plugin/badge/BadgeImpl.java
```

I resolved them and finally the build process worked. So, two things:
1. I think the problems with symbolic links should be solved.
2. I know this plugin rely in [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) to work on Android. I tested the produced APK in my smartphone and the badge is not shown, but the [test app for ShortcutBadger](https://github.com/leolin310148/IsBadgeWorking.Android) works very well.

![image](https://cloud.githubusercontent.com/assets/3768482/23915803/203d459a-08b8-11e7-8709-cf3f22022538.png)

I'm attaching the console output and the APK file.
[problem-building-sample-app.txt](https://github.com/katzer/cordova-plugin-badge/files/842291/problem-building-sample-app.txt)
[android-debug.zip](https://github.com/katzer/cordova-plugin-badge/files/842298/android-debug.zip)

Thanks in advance for any reply!

**Comment by katzer** [comment]
@djtruco Sorry for the symbolic links. Can happen... The rest seems to be resolved with the latest updates from ShortcutBadger.
