### ISSUE TITLE
What does hasPermission() pass to the callback?

### ISSUE THREAD

**Issue by chmac** [katzer/cordova-plugin-badge#90]
Does `hasPermission()` pass a boolean to the callback? Couldn't figure that out from the docs.

I had a quick look at the code for `ios` and I guess from my very limited knowledge of C that it probably does return a boolean but wanted to double check. Happy to submit a PR to clarify the docs once I know for sure.

**Comment by katzer** [comment]
@chmac `hasPermission()` and `registerPermission` both pass a boolean to the callback.
