### ISSUE TITLE
Upgrade ShortcutBadger dependency to 1.1.14

### ISSUE THREAD

**Issue by menzow** [katzer/cordova-plugin-badge#91]
Hey,

The ShortcutBadger lib has been updated, adding new device/vendor support. Is there any ETA on when these updates will be integrated? 

And what is the general workflow for integrating ShortcutBadger updates? I'll be willing to help out in this process and create pull requests.

Kind regards,
Menzo

**Comment by menzow** [comment]
Updating the dependency solved my issues on a samsung SM-G570Y, android 6.0.1 with com.sec.android.app.launcher. Maybe later this week I have some time to make a clean update and create a PR.

![group 2](https://cloud.githubusercontent.com/assets/5744434/24160538/6b8284e8-0e62-11e7-9632-261bf28de953.png)

**Comment by katzer** [comment]
@menzow In future you will be able to set the version via Cordova property. See https://github.com/katzer/cordova-plugin-badge/commit/b794968ec0cda7f45de949a61811fa113673a7a6
