### ISSUE TITLE
Clearing the badge does not work on iOS but on android

### ISSUE THREAD

**Issue by schmitzke** [katzer/cordova-plugin-badge#92]
The title says it all,

we are using `cordova.plugins.notification.badge.clear();`
this works on android, but not on iOS.

We currently use
Ionic 1
cordova 6.4.0
cordova-plugin-badge 0.7.4
urbanairship-cordova 5.3.1

UrbanAirship method: '+1'

Do you have an idea what could possibly go wrong? 
Thanks in advance!

http://stackoverflow.com/questions/43942038/how-to-reset-the-icon-badge-correctly

**Comment by miguelavaqrod** [comment]
Hi,

Same problem here... Almost same platform...

Any ideas?

Thanks in advance.

**Comment by katzer** [comment]
I tested it with the sample app with iOS10 and it works. So its not a general bug. Do you see anything in the logs? As its iOS maybe the permission to access the badge number has been revoked.

Please test with the upcoming v0.8 again and reopen if it still fails.
