### ISSUE TITLE
Failed to install 'cordova-plugin-badge'

### ISSUE THREAD

**Issue by anrip** [katzer/cordova-plugin-badge#94]
Failed to install 'cordova-plugin-badge': CordovaError: Failed to fetch plugin cordova-plugin-app-event@>=1.2.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

**Comment by katzer** [comment]
@anrip Couldn't reproduce. But anyway the upcoming v.0.8 does not depend on it anymore.
