### ISSUE TITLE
Huawei Tab Android Kitkat version error 

### ISSUE THREAD

**Issue by bandeto45** [katzer/cordova-plugin-badge#95]
![image](https://user-images.githubusercontent.com/28916544/26973993-d1a4814a-4d4b-11e7-8336-fea64001cced.png)

Hi Sir/Mam I'm developing android application which has a badge notification. I found an issue to the plugin although the project is successfully running but during debugging show up like on that image above.  Please help me to resolve this problem thank you.

**Comment by katzer** [comment]
@bandeto45 Thanks for the info!

**Comment by katzer** [comment]
Use v0.8.1
