### ISSUE TITLE
Plugin.xml references apple-ios

### ISSUE THREAD

**Issue by jamnat9** [katzer/cordova-plugin-badge#96]
Should this be cordova-ios? I cannot get the plugin to be added to my project.

**Comment by jamnat9** [comment]
fairly new to cordova and currently only using cordova-ios and android-ios platforms.

**Comment by katzer** [comment]
See here:
https://cordova.apache.org/docs/de/latest/plugin_ref/spec.html#motoren-und-motor--elemente

The plugin requires iOS@10.x to be installed. `cordova-ios` refers to the cordova platform, `apple-ios` refers to the SDK.
