### ISSUE TITLE
Plugin startup error on Android 4.x: no method 'includes'

### ISSUE THREAD

**Issue by andreszs** [katzer/cordova-plugin-badge#97]
On both Android emulator 4.4.2 and Android device 4.2.2 I get this errors on startup, which effectively renders the app unusable:

> Uncaught TypeError: Object mozilla/5.0 (linux; android 4.4.2; android sdk built for x86 build/kk) applewebkit/537.36 (khtml, like gecko) version/4.0 chrome/30.0.0.0 mobile safari/537.36 has no method 'includes'
> badge.js (22,0)

Please let me know to which version should I rollback. It does work on Android 5.1 and newer only, but we cannot drop support for Android 4.x just like that because the plugin is broken... Thanks.

**Comment by katzer** [comment]
See c1e52857b8fcc1090211ae8651c27af7bd516fa5.

I will release a fixed version as of now

**Comment by katzer** [comment]
v0.8.1

**Comment by andreszs** [comment]
Thanks for the fix, I have updated to version 0.8.1 and it works now.
