### ISSUE TITLE
registerPermission missing

### ISSUE THREAD

**Issue by andersborgabiro** [katzer/cordova-plugin-badge#98]
iOS complains that registerPermission() is undefined. The code should have ignored the call completely if the plugin hadn't been properly installed, as per below:
```
    if (typeof cordova.plugins.notification.badge !== "undefined" && platform === "ios") {
        //cordova.plugins.notification.badge.registerPermission();
    }
```
In an earlier build the call is clearly there, but building with the latest version on NPM (0.8.1) it fails.

For now I simply ignore calling it, but that might cause issues later.

Any ideas?

Regards,
Anders

**Comment by katzer** [comment]
@andersborgabiro The method has been renamed to `requestPermission`.

**Comment by andersborgabiro** [comment]
That explains it. Thanks.
